### ISSUE TITLE
the bot not support 4g files

### ISSUE THREAD

**Issue by vip200** [musa-42/stream-cloud#10]
the bot not support 4g files

**Comment by musa-42** [comment]
You need to update the Telethon library

**Comment by vip200** [comment]
> You need to update the Telethon library

my telethon version is 1.24.0

**Comment by vip200** [comment]
![image](https://user-images.githubusercontent.com/51438486/181913843-86daeaa3-62f7-4aff-9b60-f2154ad96056.png)
